server:
    port: 8081
    servlet:
        context-path: /jack/api
        session:
            cookie:
                name: JackCustID

spring:
    profiles:
        active: dev

mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.bean
    configLocation: classpath:mybatis-config.xml

logging:
    level:
        com.mapper: debug
    path: ./logs


