spring:
    datasource:
        name: cf_sjjy
        url: jdbc:mysql://10.5.0.62:3306/cf_sjjy?useAffectedRows=true
        username: jr_xiaofei
        password: 8WjdQk8c7wfMJV%3
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,wall,slf4j
        maxActive: 100
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
