server:
    port: 8081
    servlet:
        context-path: /jack/api
        session:
            cookie:
                name: JackCustID

spring:
    profiles:
        active: dev
        include: mybatisplus
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

#mybatis:
#    mapper-locations: classpath:mapping/*.xml
#    type-aliases-package: com.jack.bean
#    configLocation: classpath:mybatis-config.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
    level:
        com.jack.mapper: debug
    path: ./logs


